"""
Django settings for itapps project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent





# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'your_current_secret_key_value')

WEBSITE_HOSTNAME = os.environ.get('WEBSITE_HOSTNAME', None) 

DEBUG = WEBSITE_HOSTNAME == None 
if DEBUG: 

    ALLOWED_HOSTS = [] 
else: 

    ALLOWED_HOSTS = [WEBSITE_HOSTNAME] 

    CSRF_TRUSTED_ORIGINS = [f'https://{WEBSITE_HOSTNAME}'] 


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'itreporting',
    'users.apps.USersConfig',
    'crispy_forms',
    'crispy_bootstrap4',
    'rest_framework',  
    'api',  
    'rest_framework.authtoken'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'itapps.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates',  # Optional, if you want global templates
        ],
        'APP_DIRS': True,  # This will automatically search app directories for templates
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]






WSGI_APPLICATION = 'itapps.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
     'ENGINE': 'django.db.backends.mysql',
     'NAME': os.environ['AZURE_DB_NAME'],
     'HOST': os.environ['AZURE_DB_HOST'],
     'PORT': os.environ['AZURE_DB_PORT'],
     'USER': os.environ['AZURE_DB_USER'],
     'PASSWORD': os.environ['AZURE_DB_PASSWORD'],
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = '/media/'


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field
import os

# Safely fetch environment variables using .get() method
AZURE_SA_NAME = os.environ.get('AZURE_SA_NAME', None)
AZURE_SA_KEY = os.environ.get('AZURE_SA_KEY', None)

# Print the values if available
if AZURE_SA_NAME and AZURE_SA_KEY:
    print(AZURE_SA_NAME)
    print(AZURE_SA_KEY) 
else:
    print("Error: One or more environment variables are not set.")

AZURE_SA_NAME="dangobase11"
AZURE_SA_KEY="+8uV9i4LpsgFnBovQnREdnso8/UL7UxydB15xcWit6g0DaOOnsG2LL+vya9PV0rVntxdMtfrvWU++AStSn9HPQ=="



STORAGES = {
    "default": {
        "BACKEND": "storages.backends.azure_storage.AzureStorage",
        "OPTIONS": {
            "account_name": AZURE_SA_NAME,
            "account_key": AZURE_SA_KEY,
            "azure_container": "media",
        },
    },
    "staticfiles": {
        "BACKEND": "storages.backends.azure_storage.AzureStorage",
        "OPTIONS": {
            "account_name": AZURE_SA_NAME,
            "account_key": AZURE_SA_KEY,
            "azure_container": "static",
        },
    },
}



#STATIC_URL = f'https://{AZURE_SA_NAME}.blob.core.windows.net/static/'
#MEDIA_URL = f'https://{AZURE_SA_NAME}.blob.core.windows.net/media/'


CRISPY_TEMPLATE_PACK = 'bootstrap4'  # or 'bootstrap5', depending on your project

LOGOUT_REDIRECT_URL = '/login/'  # Redirects to the login page

LOGIN_REDIRECT_URL = 'profile'  # Redirect to the profile page after login

LOGIN_URL = 'login'  # Redirect users to the login page if they are not authenticated

CRISPY_ALLOWED_TEMPLATE_PACKS = 'bootstrap4'
CRISPY_TEMPLATE_PACK = 'bootstrap4'

# settings.py

CONTACT_EMAIL = 'c1016570@hallam.shu.ac.uk'  #personal email


# settings.py for development

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  # This will print emails to the console

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',  # Ensures token-based authentication
    ],
}
