# Generated by Django 5.1.2 on 2024-12-29 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itreporting', '0003_remove_module_registered_delete_moduleregistered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moduleregistered',
            name='description',
        ),
    ]
