# Generated by Django 5.1.2 on 2024-12-29 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itreporting', '0004_remove_moduleregistered_description'),
    ]

    operations = [
      #  migrations.AddField(
       #     model_name='moduleregistered',
        #    name='description2',
         #   field=models.TextField(default='open'),
        #),
    ]
