# Generated by Django 5.1.2 on 2024-12-29 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itreporting', '0005_moduleregistered_description'),
    ]

    operations = [
    #    migrations.RenameField(
     #       model_name='moduleregistered',
      #      old_name='description2',
       #     new_name='description',
        #),
    ]
