# Generated by Django 5.1.2 on 2024-12-29 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itreporting', '0006_rename_description_moduleregistered_description2'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduleregistered',
            name='opis',
            field=models.TextField(default='open'),
        ),
    ]
