# Generated by Django 5.1.2 on 2024-12-29 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itreporting', '0007_moduleregistered_opis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moduleregistered',
            old_name='opis',
            new_name='opis2',
        ),
    ]
