# Generated by Django 5.1.2 on 2024-12-29 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itreporting', '0008_rename_opis_moduleregistered_opis2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moduleregistered',
            name='opis2',
        ),
    ]
