# Generated by Django 5.1.2 on 2024-12-29 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itreporting', '0009_remove_moduleregistered_opis2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='description',
            field=models.TextField(default='open'),
        ),
    ]
