# Generated by Django 5.1.2 on 2024-12-29 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itreporting', '0010_alter_module_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='description',
        ),
    ]
