# Generated by Django 5.1.2 on 2024-12-29 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itreporting', '0011_remove_module_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='description',
            field=models.TextField(default='open'),
        ),
    ]
