# Generated by Django 5.1.2 on 2024-12-29 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itreporting', '0013_alter_course_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issues',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
