# Generated by Django 5.1.2 on 2024-12-29 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itreporting', '0014_alter_issues_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='registered',
        ),
        migrations.DeleteModel(
            name='ModuleRegistered',
        ),
    ]
