# Generated by Django 5.1.2 on 2025-01-03 13:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itreporting', '0016_moduleregistered_module_registered'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='moduleregistered',
            unique_together={('module', 'user')},
        ),
    ]
